sudo: required
dist: trusty
language: python
python:
  - 2.7
  - 3.4
  - 3.5

cache:
  apt: true
  pip: true
  directories:
    - pip_download_cache

jdk:
  - oraclejdk8

addons:
  apt_packages:
    - default-jdk
    - libgeos-c1

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE
  # Taken from django-haystack travis config
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - >
    if [[ $ES_VERSION == '>=2.0.0,<3.0.0' ]];
    then
      echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
    else
      echo "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-1.7.list
    fi
  - sudo apt-get update
  - sudo apt-get -y install elasticsearch
  - sudo service elasticsearch restart


install:
  - pip install --upgrade pip setuptools
  - pip install coveralls geopy requests tox
  - pip install "Django${DJANGO_VERSION}" "elasticsearch${ES_VERSION}"
  - python setup.py clean build install

after_success:
  coveralls

script:
  - python setup.py test

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - DJANGO_VERSION=">=1.8,<1.9" ES_VERSION=">=1.0.0,<2.0.0"
    - DJANGO_VERSION=">=1.9,<1.10" ES_VERSION=">=1.0.0,<2.0.0"
    - DJANGO_VERSION=">=1.10,<1.11" ES_VERSION=">=1.0.0,<2.0.0"
    - DJANGO_VERSION=">=1.8,<1.9" ES_VERSION=">=2.0.0,<3.0.0"
    - DJANGO_VERSION=">=1.9,<1.10" ES_VERSION=">=2.0.0,<3.0.0"
    - DJANGO_VERSION=">=1.10,<1.11" ES_VERSION=">=2.0.0,<3.0.0"
    - DJANGO_VERSION=">=1.11,<2.0" ES_VERSION=">=2.0.0,<3.0.0"

notifications:
  email: false
